# Ordenado todo os estágios que a aplicação precisa 

# Estágios: test, build, deploy, verificar se tem i18n para tudo

jobs:
  test:
    steps:
      # baixa o código
      # configuro o node / npm
      # executo o npm install
      # npm run test 

  build:
    steps:
      # baixa o código
      # configuro o node

      # executo o npm install
      - name: Instalar dependencias
      run: npm install

      # npm run build
      - name: Fazer build
      run: npm run build